"""initial analytics schema

Revision ID: 7652eba70608
Revises:
Create Date: 2026-09-10 01:15:42.043375
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '7652eba70608'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_facts',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.Enum('CREATED', 'COMPLETED', 'CANCELLED', name='appointment_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index(op.f('ix_appointment_facts_branch_id'), 'appointment_facts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_appointment_facts_employee_id'), 'appointment_facts', ['employee_id'], unique=False)
    op.create_table('client_facts',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_client_facts_branch_id'), 'client_facts', ['branch_id'], unique=False)
    op.create_table('consumable_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('consumable_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('written_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumable_facts_branch_id'), 'consumable_facts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_consumable_facts_written_at'), 'consumable_facts', ['written_at'], unique=False)
    op.create_table('invoice_facts',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('total_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('commission_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index(op.f('ix_invoice_facts_branch_id'), 'invoice_facts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_invoice_facts_employee_id'), 'invoice_facts', ['employee_id'], unique=False)
    op.create_table('processed_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('routing_key', sa.String(length=64), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_invoice_facts_employee_id'), table_name='invoice_facts')
    op.drop_index(op.f('ix_invoice_facts_branch_id'), table_name='invoice_facts')
    op.drop_table('invoice_facts')
    op.drop_index(op.f('ix_consumable_facts_written_at'), table_name='consumable_facts')
    op.drop_index(op.f('ix_consumable_facts_branch_id'), table_name='consumable_facts')
    op.drop_table('consumable_facts')
    op.drop_index(op.f('ix_client_facts_branch_id'), table_name='client_facts')
    op.drop_table('client_facts')
    op.drop_index(op.f('ix_appointment_facts_employee_id'), table_name='appointment_facts')
    op.drop_index(op.f('ix_appointment_facts_branch_id'), table_name='appointment_facts')
    op.drop_table('appointment_facts')
    # ### end Alembic commands ###
    # create_table создаёт тип неявно, а drop_table его не удаляет:
    # без этого повторный upgrade падает на DuplicateObjectError.
    sa.Enum(name="appointment_state").drop(op.get_bind(), checkfirst=True)
